### ISSUE TITLE
Javascript XMLHTTPrequest Issue.

### ISSUE THREAD

**Issue by VuNgocTuan** [emqtt/emq-dashboard#124]
>  xhttp.open("GET", "http://admin:public@192.168.1.100:18083/api/listeners",true);
			xhttp.setRequestHeader( 'Content-Type', 'application/json' );
			xhttp.setRequestHeader ("Authorization", "Basic " + btoa('admin' + ":" + 'public'));
			xhttp.send();

Here is my code.Work in Safari, But it got error in my Chrome (Mac OS).

> - XMLHttpRequest cannot load http://192.168.1.100:18083/api/listeners. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 401.
>- OPTIONS http://192.168.1.100:18083/api/listeners 401 (Unauthorized)

Any help?

**Comment by llongoria** [comment]
is there any solution?

**Comment by Gilbert-Wong** [comment]
@llongoria This is an authentication error, please read [document](http://emqtt.io/docs/v2/rest.html#basic-authentication) more carefully, the api use basic authentication, it absolutely you set wrong basic authentication data on your http header. Please check your http header again, I suggest you to use [insomnia](https://github.com/getinsomnia/insomnia) to verfiy the api of emqx. Then I would close this issue. If you still have questions, please open a new issue and provide more details.
