### ISSUE TITLE
MQTT user management by HTTP API and Dashboard

### ISSUE THREAD

**Issue by emqplus** [emqtt/emq-dashboard#18]
Please check issue: https://github.com/emqtt/emqttd/issues/229

Dashboard should provide api and page to add/delete/update mqtt_user if emqttd_auth_username module is enabled.

**Comment by huangdan** [comment]
@erylee  need  provide show page?

**Comment by erylee** [comment]
no. suspend this issue.

**Comment by syepes** [comment]
Is this issue going to be in the 0.16.0 release
