### ISSUE TITLE
Enabling selective TLS versions/ciphers on 18084 and 8084

### ISSUE THREAD

**Issue by rejji** [emqtt/emq-dashboard#182]
emq_dashboard.conf does not have an option to selectively enable a version for tls protocol and the ciphers (as it is available in emq.conf for 8883).

This is reqd to remove the protocol versions and ciphers that are not approved on production. Could you plan to make it available. Pls include the support for both https-dashboard and https-publish. 

Thanks
Rajeev

**Comment by rejji** [comment]
Could you provide some update or reference here.

**Comment by emqplus** [comment]
@rejji The issue will be fixed in R2.3.3 release

**Comment by rejji** [comment]
Thanks Feng for the update. Looking forward.

**Comment by emqplus** [comment]
@rejji EMQ v2.3.3 has been released, please download from http://emqtt.io/downloads.

**Comment by rejji** [comment]
Awesome. Thanks a lot. Given a chance and time at my side I will turn back the favor by contributing more than now.

**Comment by rejji** [comment]
Is there a change from 2.1.2 to 2.3.3 for this:

curl --tlsv1.2 -u any:any -d "qos=1&retain=0&topic=AABtest&message=Test" -k https://<broker>:8084/mqtt/publish

returns OK for 2.1.2 and NotFound for 2.3.3

**Comment by emqplus** [comment]
@rejji Please check the `HTTP API` on the dashboard: http://127.0.0.1:18083/#/http_api. The ports for HTTP API is 18083 or 8080.
