### ISSUE TITLE
obsolete status?

### ISSUE THREAD

**Issue by Ashtonian** [emqtt/emq-dashboard#242]
Are there any additional details on the dashboard feature and 3.0 - is there a discussion or any talk of a replacement or alternative UI?

**Comment by wiviwiv** [comment]
emqx30 changed the UI, upgraded the REST API version accordingly, and migrated to this repository:

https://github.com/emqx/emqx-dashboard/tree/emqx30

**Comment by Ashtonian** [comment]
thank you!
