### ISSUE TITLE
Where are the docs on placeholder vars like $client/ for topics??

### ISSUE THREAD

**Issue by dreamcatcha** [emqtt/emq-dashboard#245]
When a client connects to the broker a topic is created '$client/<client_id>' as can be seen in the dashboard, where can I find more information about this? And is it used in both version of emq 2.3 and emqx 3.0?

Cheers

**Comment by Gilbert-Wong** [comment]
The projects of emqtt would not be maintain, we maintain projects of emqx organization. Please open issue [here](https://github.com/emqx/emqx-dashboard/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)
