### ISSUE TITLE
Include client IP in auth failure log

### ISSUE THREAD

**Issue by lpfeup** [emqtt/emq-dashboard#59]
It would be useful to have the client IP included in the HTTP Auth failure log. For example:

<pre>
01:57:30.187 <0.361.0> [error] <b>(127.0.0.1)</b> HTTP Auth failure: username=xx, reason="Username Not Found"
</pre>

I am interested in this, because I want to protect the interface with fail2ban.

**Comment by emqplus** [comment]
@lpfeup The issue is fixed in 2.3.0 release.
