### ISSUE TITLE
MQTT User Management via HTTP API Design suggestion

### ISSUE THREAD

**Issue by frenchbread** [emqtt/emq-dashboard#90]
Related to https://github.com/emqtt/emq-dashboard/issues/18

Since MQTT by default does not provide HTTP API endpoints for managing users (add/edit/remove), we (@apinf) would like to contribute with this by extending existing HTTP API. We already added an endpoint for adding users, e.g:

```erl
handle_request("/api/add_user", Req, _State) ->
    Username = bin(Req:get_header_value("username")),
    Password = bin(Req:get_header_value("password")),
    emq_dashboard_user:add(Username, Password, <<"">>),
    respond(Req, 200, [{username, Username},{status, bin("Ok")}]);
```

It works, but could you please give some feedback on this approach?

For other endpoints like adding ACL rules, topics etc., we want to add them similarly using existing erlang API.

Also referring to the code there are two functions that basically do the same thing: `emq_dashboard_user:add/3` and `emq_auth_username:add_user/2`. First one adds user to DB, so it's also visible on a dashboard. The second one also adds it to DB, but added user is not showing up on a dashboard. What's the purpose of this and how to make it so that when user is added with `emq_auth_username:add_user`, it is also visible on a dashboard (not only in cli interface)?

**Comment by brylie** [comment]
We need a REST API in order to build an integration between EMQ and our project. We are not using the 'emq dashboard' directly, but would like to perform actions such as creating users, defining ACL rules, and creating topics from our project, via the REST API.

**Comment by emqplus** [comment]
@brylie @frenchbread We are working on the the management/monitor API these days.

**Comment by frenchbread** [comment]
@emqplus Could you please give some feedback on the idea/approach described above?

**Comment by brylie** [comment]
> We are working on the the management/monitor API these days.

Great news! We would like to help. Is there a branch where we may see the work in progress?

**Comment by ccsr** [comment]
@emqplus can you please give some schedule regarding this?

**Comment by junaidnasir** [comment]
+1, would love http api for users and acl

**Comment by brylie** [comment]
@junaidnasir, you might be interested in our [EMQ REST API](https://github.com/Digipalvelutehdas/emq-rest-api) project.

**Comment by emqplus** [comment]
@brylie We plan to release the REST APIs for management/monitoring/control in version 2.2:) BTW, could you send us a REST API design guide for APInf platform?

**Comment by brylie** [comment]
> could you send us a REST API design guide for APInf platform

Sure. What would be helpful for us to include in the design guide?

cc: @kyyberi

**Comment by emqplus** [comment]
@brylie It's okay, Thanks.
